version: 1
disable_existing_loggers: false

formatters:
  detail:
    format: "%(asctime)s | %(levelname)-8s | %(name)s:%(funcName)s:%(lineno)d - %(message)s"
  simple:
    format: "%(levelname)-8s | %(message)s"

handlers:
  simple:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: detail
    filename: app.log

loggers:
  console_logger:
    handlers: [simple, file]
    level: DEBUG
    propagate: false
  uvicorn:
    error:
      propagate: true

root:
  level: INFO
  handlers: [simple, file]
  propagate: no
